### ISSUE TITLE
Add updated content for Journeymap 5.8.5

### ISSUE THREAD

**Issue by mysticdrew** [TeamJM/journeymap-docs#6]
5.7.0 and 5.7.1 is for minecraft 1.12.2, 1.14.4, 1.15.2. There is no journeymap for mc 1.13.x

There were quite a few additions between 5.7.1 and 5.8.5. 1.16.5-5.8.5 has 6 patch versions p1-6. Mostly bug fixes specific for pixelmon. 

Review release notes for the changes between 5.7.1 and 5.8.5. 
This should not document change by change for each version. All changes will be encompassed by 5.8.5.

- [x] Waypoint Command Document (see below)
- [x] Options screen updates/additions.
- [x] Server Admin Changes, including server Option screen. 
- [x] Multiplayer Options
- [x] External Waypoint Packet listener details. (see below)

#### 5.7.2 changelog
https://discord.com/channels/239040424214396929/324317166352728065/867588836460593152

5.7.3-5.8.0 were mostly bug fixing

#### Some Key Changes 5.8.0
- Right clicking on Fullscreen map + options
- Minimap Position Button/Screen
- New Biome MapType
- Option Screen layout changes
- Chunk Data Caching
- Multiplayer Options
- Temp Waypoints
- Fullscreen key to disable buttons
- Disable Strike Through on waypoints in the waypoint manager
- New Server Options - max render distance, hide underground players
- Map Biome Water Colors
- Moon Phase info slot added

The Version Packet was removed, ignore that in the change logs

5.8.0 changes start here. (There is no full change log, CF seems to have wiped all change logs, so will have to look at discord beta release change logs)
https://discord.com/channels/239040424214396929/324317166352728065/915320032567894096
https://www.curseforge.com/minecraft/mc-mods/journeymap/files/3696405

##### First version of JourneyMap for Fabric  released
https://discord.com/channels/239040424214396929/324317166352728065/867588836460593152
- MultiWorld support Option
- Folder naming for singleplayer
- Native quark icon support
- Waypoint Icon Scaling

Add info for any new options added and major user facing changes. 

This will required documentation of the waypoint command 
https://discord.com/channels/239040424214396929/329770656541442048/864158308821368864

New waypoint endpoint that is open for server plugins to use (bukkit/paper/spigot). 
Details will be added to this issue. 

Updates to the options screens. 
And any other added/changed features that should be documented. 

See #Announcements in the journeymap discord for change logs for 5.7.2-5.8.5

**Comment by mysticdrew** [comment]
waypoint creation/deletion packet was added in 5.7.2
Waypoint Packet details
[waypoint_packet.txt](https://github.com/TeamJM/journeymap-docs2/files/10759415/waypoint_packet.txt)

How to implement in bukkit/craftbukkit. 
[bukkit_implementation.txt](https://github.com/TeamJM/journeymap-docs2/files/10759428/bukkit_implementation.txt)

**Comment by mysticdrew** [comment]
Example waypoint payload -- this will likely change in 6.0.
Note: the "icon" field difference between this and the above text file. The text file one is not a valid icon any longer. 

```
{
  "id": "home_-10,70,32",
  "name": "home",
  "icon": "journeymap:ui/img/waypoint-icon.png",
  "enable": true,
  "type": "Normal",
  "origin": "external",
  "x": -10,
  "y": 70,
  "z": 32,
  "r": 85,
  "g": 255,
  "b": 255,
  "persistent": false,
  "dimensions": [
    "minecraft:overworld"
  ]
}
```

**Comment by stantios** [comment]
This can be closed as it was implemented in https://github.com/TeamJM/journeymap-docs/pull/34
